#!/bin/sh

#
# Calls the piaware-restart-network executable to appropriately apply and restart networking
# for the appropriate OS distribution
#

status=0

if [ -f /usr/bin/piaware-restart-network ]; then
	/usr/bin/piaware-restart-network
else
	status=1
	echo "Missing service to restart networking. Try rebooting device to apply changes."
fi

exit $status
